### ISSUE TITLE
[Android] Example project not receiving Push Notification when app is terminated

### ISSUE THREAD

**Issue by desmondtayweechuan** [pushy-me/pushy-flutter#19]
Hello Pushy Team,

I have encountered problem when running the example application. I am not able to receive any push notifications when the app is terminated. However, I am able to receive push notification normally when the app is in foreground and background. I have also changed the default package name from `me.pushy.example` to my own test package name `com.example.pushytest`.

I have tested it on Google Pixel and Redmi phone, both yield the same result just the PID is different. Below is the logs I received when the app is terminated and a push notification is send.

### Flutter logs
`flutter logs`
```
E/AndroidRuntime(13614): FATAL EXCEPTION: main
E/AndroidRuntime(13614): Process: com.example.pushytest, PID: 13614
E/AndroidRuntime(13614): java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference
E/AndroidRuntime(13614):        at io.flutter.embedding.engine.loader.FlutterLoader.findAppBundlePath(FlutterLoader.java:324)
E/AndroidRuntime(13614):        at io.flutter.view.FlutterMain.findAppBundlePath(FlutterMain.java:103)
E/AndroidRuntime(13614):        at me.pushy.sdk.flutter.util.PushyFlutterBackgroundExecutor.startBackgroundIsolate(PushyFlutterBackgroundExecutor.java:76)
E/AndroidRuntime(13614):        at me.pushy.sdk.flutter.util.PushyFlutterBackgroundExecutor.startBackgroundIsolate(PushyFlutterBackgroundExecutor.java:55)
E/AndroidRuntime(13614):        at me.pushy.sdk.flutter.PushyPlugin$3.run(PushyPlugin.java:314)
E/AndroidRuntime(13614):        at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(13614):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(13614):        at android.os.Looper.loop(Looper.java:201)
E/AndroidRuntime(13614):        at android.app.ActivityThread.main(ActivityThread.java:6810)
E/AndroidRuntime(13614):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13614):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AndroidRuntime(13614):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

### Additional
`flutter doctor`

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-SG)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 12.0)
    ! CocoaPods 1.7.0 out of date (1.8.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2020.1.2)
[✓] VS Code (version 1.51.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by pushy-me** [comment]
Hi @desmondtayweechuan,
Thanks for filing this issue.

As per a similar issue reported in https://github.com/transistorsoft/flutter_background_fetch/issues/160, it appears this error occures in Flutter versions `1.22.x` and up.

The solution is to ensure you have an `Application` class created and configured in the `AndroidManifest.xml`:
https://github.com/transistorsoft/flutter_background_fetch/issues/160#issuecomment-717227807

Please let us know if it resolves the issue.

**Comment by desmondtayweechuan** [comment]
By adding the `Application` class and configured the `AndroidManifest.xml`, it works. Thanks @pushy-me
