### ISSUE TITLE
[Android] Application crashes on startup when building with last Flutter 1.12.13

### ISSUE THREAD

**Issue by EgorGrisina** [pushy-me/pushy-flutter#2]
Hi! We got a problem after updating to the latest version of **Flutter 1.12.13**, there is a crash on launch the application after successful build. 

### Steps to Reproduce
1. upgrade flutter with
```
flutter upgrade
```
2. upgrade dependences and cache
```
flutter pub cache repair
flutter pub upgrade
flutter pub get
```
3. Build and launch any application with the Pushy SDK dependecy, `pushy-demo-flutter` for example
```
flutter clean
flutter build apk
flutter install
```
4. Crash at application startup.

### Logs 
through Logcat
```
E/Pushy: Failed to invoke getFlutterView() on parent activity
    java.lang.NoSuchMethodException: getFlutterView []
        at java.lang.Class.getMethod(Class.java:1981)
        at java.lang.Class.getMethod(Class.java:1637)
        at me.pushy.sdk.flutter.g.a(:55)
        at me.pushy.sdk.flutter.g.a(:46)
        at b.a.c.a.a(:14)
        at me.pushy.example.MainActivity.onCreate(:11)
        at android.app.Activity.performCreate(Activity.java:6706)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1122)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2837)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2949)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1655)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6472)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1114)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

```

### Additional

Reproduced both for `io.flutter.app.FlutterActivity` and `io.flutter.embedding.android.FlutterActivity`

flutter doctor 
```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.476], locale ru-RU)
    • Flutter version 1.12.13+hotfix.5 at D:\flutter
    • Framework revision 27321ebbad (2 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\Users\Egor\AppData\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • M6T • 811HEBT623EQ8 • android-arm64 • Android 7.0 (API 24)

• No issues found!
```

Please check updates for using the platform_channel in the Flutter SDK, thanks!
https://github.com/flutter/flutter/tree/master/examples/platform_channel

**Comment by pushy-me** [comment]
Hi @EgorGrisina,
Thank you so much for taking the time to report this issue and provide such exact reproduction steps! 💯 

We've reproduced and released a fix in https://github.com/pushy-me/pushy-flutter/commit/55c319be13369e0fcfc8f46c579a295bec3b2689 which has been published as `pushy_flutter: 1.0.3`.

Please edit the `pubspec.yaml` in the root directory of your project and update the plugin version referenced to the following:

```
pushy_flutter: 1.0.3
```

Flutter now comes preconfigured with **ProGuard**. Please make sure the following lines are present in your `android/app/proguard-rules.pro` file (please create this file if it doesn't exist yet):

```
-dontwarn me.pushy.**
-keep class me.pushy.** { *; }
```

Then, run:
```
flutter pub get
flutter clean
flutter build apk
flutter install
```

Your app should run now 🎉
